import type { NextPage } from "next";
import Head from "next/head";
import { MouseEventHandler } from "react";
import { useDarkMode } from "../hooks/useDarkMode";

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Invoice App - Frontend Mentor Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
   
      </main>
    </div>
  );
};

export default Home;
