import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Invoice App - Frontend Mentor Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Main>
        <div className="container">
          <div className="header-text-wrapper">
            <h2 className="header-heading">Invoices</h2>
            <p className="header-details">There are 8 total invoices</p>
          </div>
          <button className="filter-button">
            Filter{" "}
            <span className="filter-arrow-icon-wrapper">
              <Image
                src="/assets/icon-arrow-down.svg"
                alt="arrow"
                objectFit="contain"
                width={12}
                height={12}
              />
            </span>
          </button>
          <button className="add-button">
            <span className="circle" />
            New
          </button>
        </div>
      </S.Main>
    </div>
  );
};

export default Home;
const S = {
  Main: styled.main`
    margin-top: 4rem;
    .container {
      display: grid;
      align-items: center;
      justify-content: center;
      grid-template-columns: 0.4fr 0.3fr 0.3fr;
      button {
        cursor: pointer;
        border: none;
        outline: none;
      }
      .header-text-wrapper {
        .header-heading {
          margin-bottom: 0.5rem;
          font-size: 1.25rem;
          color: rgb(12, 14, 22);
          font-weight: bold;
          font-size: 2rem;
          line-height: 1.125;
          letter-spacing: -1px;
        }
        .header-details {
          color: rgb(136, 142, 176);
          font-size: 0.75rem;
          line-height: 1.125;
          letter-spacing: -0.25px;
        }
      }
      .filter-button {
        max-width: 120px;
        min-width: 60px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0 1rem;
        background: none;
        height: 2rem;
        .filter-arrow-icon-wrapper {
          display: inline-block;
        }
      }
      .add-button {
        display: flex;
        align-items: center;
        justify-content: space-evenly;
        border-radius: 10rem;
        font-size: 0.75rem;
        font-weight: 700;
        line-height: 1.25;
        color: white;
        min-width: 5.875rem;
        padding: 0.5rem 1rem 0.5rem 0.5rem;
        background: rgb(124, 93, 250);
        transition: background 0.3s ease 0s, color 0.3s ease 0s;
        .circle {
          display: inline-block;
          position: relative;
          background: white;
          width: 30px;
          height: 30px;
          border-radius: 50%;
          color: rgb(124, 93, 250);
          ::after,
          ::before {
            content: "";
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
          }
          ::after {
            width: 9px;
            height: 2px;
            background: rgb(124, 93, 250);
          }
          ::before {
            width: 2px;
            height: 9px;
            background: rgb(124, 93, 250);
          }
        }
      }
    }
  `,
};
